apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: space-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
      containers:
        - name: log-output
          image: velivalentine/log-output@sha256:f529310a8018746ec5f27699c00db8992c01544f5d19cc55a411598487544cbc
          resources:
            limits:
              memory: "300M"
              cpu: "1"
          volumeMounts:
            - mountPath: /usr/src/logs
              name: shared-logs
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
            - name: LOG_PATH
              value: "/usr/src/logs/shared.log"
            - name: PING_PONG_URL
              value: http://ping-pong-app-service:2345/
        - name: log-writer
          image: velivalentine/log-writer:1.10-prod
          resources:
            limits:
              memory: "300M"
              cpu: "1"
          volumeMounts:
            - mountPath: /usr/src/logs
              name: shared-logs
          env:
            - name: LOG_PATH
              value: "/usr/src/logs/shared.log"
