apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: space-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
      containers:
        - name: log-output
          image: velivalentine/log-output@sha256:05ff400aa3bc643b2f2f8bc52b8d70a0d7a1ea2ea2caf103c7d25a75fd7f5579
          resources:
            limits:
              memory: "300M"
              cpu: "1"
          volumeMounts:
            - mountPath: /usr/src/logs
              name: shared-logs
          env:
            - name: LOG_PATH
              value: "/usr/src/logs/shared.log"
            - name: PING_PONG_URL
              value: http://ping-pong-app-service:2345/
        - name: log-writer
          image: velivalentine/log-writer:1.10-prod
          resources:
            limits:
              memory: "300M"
              cpu: "1"
          volumeMounts:
            - mountPath: /usr/src/logs
              name: shared-logs
          env:
            - name: LOG_PATH
              value: "/usr/src/logs/shared.log"
