apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-service
  namespace: project-1
  labels:
    app: todo-postgres
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: todo-postgres-app