apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm
  namespace: project-1
spec:
  interval: 1m
  url: https://nats-io.github.io/k8s/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: project-1
spec:
  interval: 30s
  chart:
    spec:
      chart: nats
      version: '0.17.x'
      sourceRef:
        kind: HelmRepository
        name: helm
        namespace: project-1
      interval: 1m
  values:
    replicaCount: 1