apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-app-dep
  namespace: project-1
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster-app
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster-app
    spec:
      containers:
      - env:
        - name: NATS_URL
          value: nats://nats:4222
        image: broadcaster-image
        name: broadcaster-app
        resources:
          limits:
            cpu: 10m
            memory: 100Mi